### ISSUE TITLE
ios 初始化报错

### ISSUE THREAD

**Issue by NiBoTe** [fluttercandies/flutter_bdface_collect#10]
resource_path == nil
oc->bdface_auth_get_error_msg auth remote data get error -- read file error: -1 -- local auth failed: 12 -> err_no: 700 -> err_msg: wrong match of appkey/packedge_name/signature_md5 -- remote auth failed: 13
oc->bdface_auth_get_local_info alg_id=3 key=QIANQIAN2-FACE-IOS pk=com.fluttercandies.flutter-bdface-collect-example md5=00000000000000000000000000000000 device_id=4E219A60F8893264E011A17CDE164CDE1F8376CD
os->sample-init license errorCode=13
[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 93 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 93 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
flutter: 初始化结果失败
oc->bdface_create_instance errorCode:-13
os->faceApi is nil
oc->bdface_create_instance errorCode:-13
os->faceApi is nil

**Comment by CyJaySong** [comment]
https://cloud.baidu.com/doc/FACE/s/pkd3xtfgn#5常见问题

**Comment by NiBoTe** [comment]
麻烦帮我看看这个是啥问题，文档看了还是有疑问

**Comment by CyJaySong** [comment]
如果没什么问题，我就关闭了
