### ISSUE TITLE
install! 'cocoapods', :disable_input_output_paths => true

### ISSUE THREAD

**Issue by lovachen** [fluttercandies/flutter_bdface_collect#11]
install! 'cocoapods', :disable_input_output_paths => true添加会导致应用图标无法输出，应用图片文件无法输出

**Comment by CyJaySong** [comment]
见 https://github.com/fluttercandies/flutter_bdface_collect/issues/7

**Comment by lovachen** [comment]
> 见 #7

改了的
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    error: Multiple commands produce '/Users/chentaisu/Desktop/test/testapp/build/ios/Release-iphoneos/Runner.app/Assets.car':
    1) Target 'Runner' (project 'Runner') has compile command with input '/Users/chentaisu/Desktop/test/testapp/ios/Runner/Assets.xcassets'
    2) That command depends on command in Target 'Runner' (project 'Runner'): script phase “[CP] Copy Pods Resources”

    warning: duplicate output file '/Users/chentaisu/Desktop/test/testapp/build/ios/Release-iphoneos/Runner.app/Assets.car' on task:
    PhaseScriptExecution [CP] Copy Pods Resources
    /Users/chentaisu/Library/Developer/Xcode/DerivedData/Runner-axzfdodthzwcyaaoafagklqtctgo/Build/Intermediates.noindex/Runner.build/Release
    -iphoneos/Runner.build/Script-59880E526245ACEE610E2864.sh (in target 'Runner' from project 'Runner')


It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.
chentaisudeMacBook-Pro:ios chentaisu$
