### ISSUE TITLE
iOS端授权失败

### ISSUE THREAD

**Issue by ztj8096** [fluttercandies/flutter_bdface_collect#12]
不知道是否因为百度的库更新了，目前iOS端不好用，framework这些都没加入资源，认证失败

**Comment by CyJaySong** [comment]
请检查自己是否配置正确，依赖的库放在插件的包里，百度升级了库不受影响的。目前该插件我已用于生产环境，没有问题的

**Comment by ztj8096** [comment]
是的，插件正常使用，是我这边配置的问题，感谢！



在 2022-02-21 22:36:49，"CyJaySong" ***@***.***> 写道：

请检查自己是否配置正确，依赖的库版放在插件的包里，百度升级了库不受影响的。目前该插件我已用于生产环境，没有问题的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
