### ISSUE TITLE
ios 人脸采集页，关闭按钮没有事件回调

### ISSUE THREAD

**Issue by ccwawamiya** [fluttercandies/flutter_bdface_collect#14]

**Comment by CyJaySong** [comment]
你的意思是，采集的时候，点击了关闭按钮，没有反应？

**Comment by ccwawamiya** [comment]
flutter_bdface_collect.dart 文件 第50行，
final Map<String, dynamic>? result = await _methodChannel.invokeMapMethod(
        MethodConstants.Collect, config.toMap());
这里 会因为ios 采集界面关闭之后，获取不到 result .

ios/Classes/BDFaceFaceSDKUI/UI/Controller/BDFaceBaseViewController.m 里closeAction 可以增加一个一行
self.completion(NULL);

**Comment by CyJaySong** [comment]
@ccwawamiya 方便提一个PR么

**Comment by CyJaySong** [comment]
@ccwawamiya 如果可以的话，old-sdk也看看吧

**Comment by ccwawamiya** [comment]
PR已提

**Comment by CyJaySong** [comment]
@ccwawamiya 感谢，old-sdk分支有那个问题没呢
