### ISSUE TITLE
采集的图片，只有1kb 是否有问题？需要怎么配置吗？

### ISSUE THREAD

**Issue by yj229201093** [fluttercandies/flutter_bdface_collect#17]
采集的图片，只有1kb 是否有问题？需要怎么配置吗？

**Comment by yj229201093** [comment]
采集出来的图片是加密的base64吗？创给后台需要解密吗？

**Comment by CyJaySong** [comment]
@yj229201093 取决于你传递的参数，你可以参考 `FaceConfig` 的属性说明，采集的图片默认是不加密的

**Comment by yj229201093** [comment]
用的默认配置

**Comment by CyJaySong** [comment]
那就是正常的呀，你可以把那个Base64显示出来看看

**Comment by yj229201093** [comment]
base64 转了，图片显示不出来。
/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAUAAtADASIAAhEBAxEB/8QAHQAAAgIDAQEBAAAAAAAAAAAAAwQCBQABBgcICf/EAEEQAAEDAwMDAwIFAwMEAgEBCQEAAhEDITEEEkEFUWEGInETgRQykaGxB0LBI1LRFeHw8TNiJHJDghYlNWNzkqL/xAAaAQADAQEBAQAAAAAAAAAAAAAAAQIDBAUG/8QAJxEBAQACAgIDAQACAwEBAQAAAAECESExA0ESUWFxBCITFDKBkUL/2gAMAwEAAhEDEQA/APX9gLbX7rNocbNtwpWEN/YLYAxeObrzPx08Xpn05MbYjIU2n73MfCxtiIiJx3UyN5Htx9lOrtWtdsDXBp3ERa6lt3iwgHKiCSABDQeP8okDbER+yOYfHTRp+NpN0UkuaBziBdQAk7hc4RRO8ECBFiqhan/6jRb9ObfZTE2afuMKTWHbAzmVEsIcCbj5S0n/AM8JBsiztoHKkGFzhINhzyttbYHELGiZIGU5yekvysFxOJH8KTKcj3Zn9VoO5iI5U2CbkDbwBlHUGmMafzE3vHhKdWds0lokuAElOAXMAnyq/qLxUq0aU7oEmO6ZKXr9UafptWIa+OTZa6JpvwvS6W7LhJPkpT1LUFd+m0zWwXuuFc0R7KVINtYBPaNSel30mjt0zGgAePKsw0ji3KW01P6dNoJiBYd0

这样的base64有问题的，就是采集后回调的。

static Future<String> createFileFromString(String base64Str) async {
    Uint8List bytes = base64.decode(base64Str);
    String dir = (await getApplicationDocumentsDirectory()).path;
    File file = File(
        "$dir/" + DateTime.now().millisecondsSinceEpoch.toString() + ".png");
    await file.writeAsBytes(bytes);
    return file.path;
  }
数据确实有，

**Comment by yj229201093** [comment]
辛苦大佬

**Comment by CyJaySong** [comment]
你是直接打印的么？建议把直接输出到文件，再看，打印时可能会被截断

**Comment by yj229201093** [comment]
可以了，照片出来了。谢谢 辛苦了
