### ISSUE TITLE
把 flutter_bdface_collect: ^1.1.1 注释掉，就不会报错

### ISSUE THREAD

**Issue by CoderXSLee** [fluttercandies/flutter_bdface_collect#18]
Could not build the precompiled application for the device.
Error (Xcode): Multiple commands produce '/Users/coderxslee/WrokSpace/youlin/build/ios/Debug-iphoneos/Runner.app/Assets.car':
1) Target 'Runner' (project 'Runner') has compile command with input '/Users/coderxslee/WrokSpace/youlin/ios/Runner/Assets.xcassets'
2) That command depends on command in Target 'Runner' (project 'Runner'): script phase “[CP] Copy Pods Resources”

**Comment by CoderXSLee** [comment]
已解决 参看https://www.jianshu.com/p/1e46bf6c48eb 第2条即可
2.修改cocoaPod的Podfile脚本
在Podfile中的platform :ios, '9.0'底下增加如下代码
install! 'cocoapods', :disable_input_output_paths => true

**Comment by CyJaySong** [comment]
@CoderXSLee README 明明有啊
