### ISSUE TITLE
android 初始化报错

### ISSUE THREAD

**Issue by wangzhaohe** [fluttercandies/flutter_bdface_collect#19]
请帮看看 Android，我实在是找不出原因了。
ios已经成功了，可以取到 base64数据

看记录好像是有3个问题：

1. W/System.err(13851): java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt (No such file or directory)

2. E/License-SDK(13851): request data {"err_no":700,"err_msg":"wrong match of appkey\/packedge_name\/signature_md5","result":[],"timestamp":1654142839,"cached":0,"serverlogid":"0439685333","error_code":700,"error_msg":"wrong match of appkey\/packedge_name\/signature_md5"}

3. E/linker  (13851): library "/system/lib/libandroid_runtime.so" ("/system/lib/libandroid_runtime.so") needed or dlopened by "/data/data/com.xcall.luding3rd2022/files/com.baidu.liantian.x0/libliantiansec35210.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]

***
Launching lib/main.dart on Mi Note 3 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:49513/V4bkSrKd8bg=/ws
Syncing files to device Mi Note 3...
D/vndksupport(13851): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(13851): Loading /vendor/lib64/hw/gralloc.sdm660.so from current namespace instead of sphal namespace.
I/l.luding3rd202(13851): ProcessProfilingInfo new_methods=1211 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (13851): 开始初始化
W/linker  (13851): Warning: "/data/app/com.xcall.luding3rd2022-qut8UK5T4OXKeLB57NgCyw==/lib/arm64/libpaddle_light_api_shared.so" unused DT entry: DT_RPATH (type 0xf arg 0x8a19) (ignoring)
E/License-SDK(13851): bd_unifylicense load start
E/License-SDK(13851): bd_unifylicense load end
I/flutter (13851): 开始初始化
W/Thread-4(13851): type=1400 audit(0.0:2082): avc: denied { search } for name="block" dev="tmpfs" ino=11894 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0
I/License-SDK(13851): Load liantian ac succeed
W/Thread-4(13851): type=1400 audit(0.0:2086): avc: denied { search } for name="block" dev="tmpfs" ino=11894 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0
E/License-SDK(13851): read_license_from_system_path FileNotFoundException
W/System.err(13851): java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt (No such file or directory)
W/System.err(13851): 	at java.io.FileInputStream.open0(Native Method)
W/System.err(13851): 	at java.io.FileInputStream.open(FileInputStream.java:231)
W/System.err(13851): 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseReaderUtils.read_license_from_system_path(LicenseReaderUtils.java:54)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseReaderUtils.get_local_license_file_inputstream(LicenseReaderUtils.java:38)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseNewReader.readFile(LicenseNewReader.java:48)
W/System.err(13851): 	at com.baidu.vis.unified.license.AndroidLicenser.nativeFaceAuthFromFile(Native Method)
W/System.err(13851): 	at com.baidu.vis.unified.license.AndroidLicenser.authFromFile(AndroidLicenser.java:114)
W/System.err(13851): 	at com.baidu.idl.main.facesdk.FaceAuth$1.run(FaceAuth.java:125)
W/System.err(13851): 	at com.baidu.idl.main.facesdk.FaceQueue$PoolWorker.run(FaceQueue.java:51)
E/License-SDK(13851): read_license_from_asset
E/License-SDK(13851): read_license_from_asset IOException
W/System.err(13851): java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt
W/System.err(13851): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(13851): 	at android.content.res.AssetManager.open(AssetManager.java:748)
W/System.err(13851): 	at android.content.res.AssetManager.open(AssetManager.java:725)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseReaderUtils.read_license_from_asset(LicenseReaderUtils.java:99)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseReaderUtils.get_local_license_file_inputstream(LicenseReaderUtils.java:45)
W/System.err(13851): 	at com.baidu.vis.unified.license.LicenseNewReader.readFile(LicenseNewReader.java:48)
W/System.err(13851): 	at com.baidu.vis.unified.license.AndroidLicenser.nativeFaceAuthFromFile(Native Method)
W/System.err(13851): 	at com.baidu.vis.unified.license.AndroidLicenser.authFromFile(AndroidLicenser.java:114)
W/System.err(13851): 	at com.baidu.idl.main.facesdk.FaceAuth$1.run(FaceAuth.java:125)
W/System.err(13851): 	at com.baidu.idl.main.facesdk.FaceQueue$PoolWorker.run(FaceQueue.java:51)
E/License-SDK(13851): open license file error.
E/License-SDK(13851): license file info =57140F3FE775DA74A225B85AA8DC6A39792F6E61D9C9FC1A1167870CB5A3AE7A83D8E844702CF84F56EECDD3491B55AB47147A34311B050CA0929B70A7690D85CBA81B932E1846DFEDB04629651BC0569F7F1960B6EEE11B5EE2D9587F4C0972CB42D10B2F2F6410AA9D13C662B7AAB72A54CD6321FAD7190D3F3835818A0918E8BF1B2669A8C13C14126DE006A2D03F3F862673CC8AD251969449D644517828684C9DFA8AB3A0DE931A9550647675B8628E4670616102FAF4302A6A4FC70C6A462A2A0A45586877F97468A2247BD27E6716A3C6F74889C901B9855C61E8D4E839B48313F0474CD071922B66A402ADA9AC717DD38BD85E758539313960FE80FE
E/License-SDK(13851): license file info =7EC7D5CB417800FC92E4F55E934494CEDE0664C2635FFE7EE39A4D86965FF9076811E788965F719AE6F5AB123B117EDF4DC6F7AD799A58BB399D15802AF16B156FCA1DE659F713253A30D147F582F24BEDA9D898AFA49CABFFDCA32AE9D88EE3459CF7B079D9CECE968472019530033B2B14C3E708473369E7BE0FC9336571AC10A462444B25BE7227023F13DC9462BF3CE58C1F8A283D3FF84F37735A74773779927ED285076BC07AC0D6119B2FAAE4A06FADBC529175F263327C111D6E6DDDF8EFF1978A2DA67621CD519A6356A03E2B8F882E18DD068C0C742C029BC0B74B68D1B2085BB19FDB05F1184FB27A2F491F0E5406C97836723FD281B8804071C9
D/NetworkSecurityConfig(13851): No Network Security Config specified, using platform default
E/License-SDK(13851): request get_remote_license =https://aip.baidubce.com/public/2.0/license/face-api/app/querydevicelicense
W/l.luding3rd202(13851): Accessing hidden field Landroid/content/pm/ApplicationInfo;->primaryCpuAbi:Ljava/lang/String; (light greylist, reflection)
W/l.luding3rd202(13851): Unsupported class loader
W/l.luding3rd202(13851): Skipping duplicate class check due to unsupported classloader
E/License-SDK(13851): request code 200
E/License-SDK(13851): request data {"err_no":700,"err_msg":"wrong match of appkey\/packedge_name\/signature_md5","result":[],"timestamp":1654142839,"cached":0,"serverlogid":"0439685333","error_code":700,"error_msg":"wrong match of appkey\/packedge_name\/signature_md5"}
E/jni     (13851): java result = {"err_no":700,"err_msg":"wrong match of appkey\/packedge_name\/signature_md5","result":[],"timestamp":1654142839,"cached":0,"serverlogid":"0439685333","error_code":700,"error_msg":"wrong match of appkey\/packedge_name\/signature_md5"}
I/FaceSDK (13851): licenseKey:LUDING3RD2022-FACE-ANDROID,algorithmId:3;packageName:com.xcall.luding3rd2022,md5:18074EA6EA7A2A1098BD3B7248EEB4D5;deviceId:11140C1F12FEEB2C52DFBE67ED3E636897,fingerVersion:3.5.7.5;licenseSdkVersion:5.5.0.1-mobile-collection
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/res/AssetManager;-><init>()V (light greylist, reflection)
E/l.luding3rd202(13851): Invalid ID 0x00000000.
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/res/AssetManager;->addAssetPath(Ljava/lang/String;)I (light greylist, reflection)
E/l.luding3rd202(13851): Invalid ID 0x00000000.
E/l.luding3rd202(13851): Invalid ID 0x00000000.
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/pm/PackageParser;-><init>()V (light greylist, linking)
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/pm/PackageParser;->parsePackage(Ljava/io/File;I)Landroid/content/pm/PackageParser$Package; (light greylist, linking)
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/pm/PackageUserState;-><init>()V (light greylist, linking)
W/l.luding3rd202(13851): Accessing hidden method Landroid/content/pm/PackageParser;->generatePackageInfo(Landroid/content/pm/PackageParser$Package;[IIJJLjava/util/Set;Landroid/content/pm/PackageUserState;)Landroid/content/pm/PackageInfo; (light greylist, linking)
E/l.luding3rd202(13851): Invalid ID 0x00000000.
W/sec-1-thread-4(13851): type=1400 audit(0.0:2097): avc: denied { getattr } for path="/system/bin/dun-server" dev="dm-0" ino=6906 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:dun-server_exec:s0 tclass=file permissive=0
W/sec-1-thread-4(13851): type=1400 audit(0.0:2098): avc: denied { getattr } for path="/system/bin/statsd" dev="dm-0" ino=6909 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:statsd_exec:s0 tclass=file permissive=0
W/sec-1-thread-4(13851): type=1400 audit(0.0:2099): avc: denied { getattr } for path="/system/bin/dumpstate" dev="dm-0" ino=6910 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:dumpstate_exec:s0 tclass=file permissive=0
W/sec-1-thread-4(13851): type=1400 audit(0.0:2100): avc: denied { getattr } for path="/system/bin/bpfloader" dev="dm-0" ino=6911 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:bpfloader_exec:s0 tclass=file permissive=0
W/sec-1-thread-4(13851): type=1400 audit(0.0:2101): avc: denied { getattr } for path="/system/bin/uncrypt" dev="dm-0" ino=6916 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:uncrypt_exec:s0 tclass=file permissive=0
W/Settings(13851): Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
W/l.luding3rd202(13851): Accessing hidden method Landroid/os/ServiceManager;->getService(Ljava/lang/String;)Landroid/os/IBinder; (light greylist, reflection)
W/l.luding3rd202(13851): Accessing hidden method Landroid/os/ServiceManager;-><init>()V (light greylist, reflection)
E/libc    (13851): Access denied finding property "persist.service.bdroid.bdaddr"
W/sec-1-thread-4(13851): type=1400 audit(0.0:2186): avc: denied { read } for name="u:object_r:bluetooth_prop:s0" dev="tmpfs" ino=11916 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:bluetooth_prop:s0 tclass=file permissive=0
W/sec-1-thread-4(13851): type=1400 audit(0.0:2187): avc: denied { search } for name="asound" dev="proc" ino=4026532036 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:proc_asound:s0 tclass=dir permissive=0
W/l.luding3rd202(13851): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (light greylist, reflection)
W/l.luding3rd202(13851): Accessing hidden field Landroid/app/ActivityThread;->mPackages:Landroid/util/ArrayMap; (light greylist, reflection)
E/linker  (13851): library "/system/lib/libandroid_runtime.so" ("/system/lib/libandroid_runtime.so") needed or dlopened by "/data/data/com.xcall.luding3rd2022/files/com.baidu.liantian.x0/libliantiansec35210.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
I/chatty  (13851): uid=10237(com.xcall.luding3rd2022) sec-1-thread-4 identical 2 lines
E/linker  (13851): library "/system/lib/libandroid_runtime.so" ("/system/lib/libandroid_runtime.so") needed or dlopened by "/data/data/com.xcall.luding3rd2022/files/com.baidu.liantian.x0/libliantiansec35210.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
E/linker  (13851): library "/system/lib/libgui.so" ("/system/lib/libgui.so") needed or dlopened by "/data/data/com.xcall.luding3rd2022/files/com.baidu.liantian.x0/libliantiansec35210.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
E/linker  (13851): library "/system/lib/libgui.so" ("/system/lib/libgui.so") needed or dlopened by "/data/data/com.xcall.luding3rd2022/files/com.baidu.liantian.x0/libliantiansec35210.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]

**Comment by CyJaySong** [comment]
wrong match of appkey

**Comment by CyJaySong** [comment]
另外，签名是不是使用debug的签名，百度授权的签名对不对得上

**Comment by wangzhaohe** [comment]
> 另外，签名是不是使用debug的签名，百度授权的签名对不对得上

 我是在 Android Studio 上直接点击运行的。请问还需要配置 /Users/swot/project/luding3rd2022/android/app/build.gradle 文件吗？

**Comment by wangzhaohe** [comment]
1. 百度授权文件位置 app/src/main/assets/idl-license.face-android
2. app/src/main/AndroidManifest.xml

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.xcall.luding3rd2022">
       <application
            android:label="luding3rd2022"
            android:usesCleartextTraffic="true"
            android:name="${applicationName}"
            android:icon="@mipmap/ic_launcher">
            <activity
                android:name=".MainActivity"
                android:exported="true"
                android:launchMode="singleTop"
                android:theme="@style/LaunchTheme"
                android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                android:hardwareAccelerated="true"
                android:windowSoftInputMode="adjustResize">
                
                <meta-data
                  android:name="io.flutter.embedding.android.NormalTheme"
                  android:resource="@style/NormalTheme"
                  />
                <intent-filter>
                    <action android:name="android.intent.action.MAIN"/>
                    <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
            </activity>
            
            <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
           <provider android:authorities="com.xcall.luding3rd2022.liantian.ac.provider"
               android:name="com.baidu.liantian.LiantianProvider" android:exported="true"/>
       </application>
    </manifest>

3. applicationId "com.xcall.luding3rd2022"

4. 百度授权

    iOS License ID: luding3rd2022-face-ios
    
    安卓 License ID: luding3rd2022-face-android
    
    iOS 包名: com.xcall.luding3rd2022
    
    安卓包名: com.xcall.luding3rd2022
    
    安卓 MD5: 5F5132FD255C0C51DC56785302FA91FA

5. main.dart

    import 'dart:io';
    import 'package:flutter/material.dart';
    import 'package:flutter/services.dart';
    import 'package:flutter_bdface_collect/flutter_bdface_collect.dart';
    import 'package:flutter_bdface_collect/model.dart';
    
    void main() {
      runApp(MyApp());
    }
    
    class MyApp extends StatefulWidget {
      @override
      _MyAppState createState() => _MyAppState();
    }
    
    class _MyAppState extends State<MyApp> {
      String _platformVersion = 'Unknown';
      @override
      void initState() {
        super.initState();
        initPlatformState();
      }
    
      Future<void> initPlatformState() async {
        String platformVersion;
        try {
          platformVersion = await FlutterBdfaceCollect.instance.platformVersion ??
              'Unknown platform version';
        } on PlatformException {
          platformVersion = 'Failed to get platform version.';
        }
        if (!mounted) return;
    
        setState(() {
          _platformVersion = platformVersion;
        });
      }
    
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          home: Scaffold(
            appBar: AppBar(
              title: const Text('百度离线人脸采集'),
            ),
            body: Center(
              child: ElevatedButton(
                child: Text('开始采集: $_platformVersion\n'),
                onPressed: () {
                  collectFace();
                },
              ),
            ),
          ),
        );
      }
    
      collectFace() async {
        print('开始初始化');
        late var licenseId;
        if (Platform.isAndroid) licenseId = "luding3rd2022-face-android";
        else if (Platform.isIOS) licenseId = "luding3rd2022-face-ios";
        String? err = await FlutterBdfaceCollect.instance.init(licenseId);
        print('初始化结果${err == null ? '成功' : '失败'}');
    
        // 这里填写百度离线采集SDK授权后的LicenseID
        // String licenseID = "luding3rd-test2-face-android";
        // String? err = await FlutterBdfaceCollect.instance.init(licenseID);
        // print('初始化结果${err == null ? '成功' : '失败'}');
        //采集配置
        FaceConfig config =
        FaceConfig(livenessTypes: Set.from(LivenessType.all.sublist(1, 4)));
        //开始采集
        CollectResult res = await FlutterBdfaceCollect.instance.collect(config);
        print('采集错误结果:${res.error.isNotEmpty} 内容：${res.error}');
        print('采集原图imageCropBase64:${res.imageSrcBase64.isNotEmpty}');
        print('采集抠图imageSrcBase64:${res.imageCropBase64.isNotEmpty}');
        // UnInit 释放
        // FlutterBdfaceCollect.instance.unInit();
      }
    }

6. keytool -list -v -keystore kbed.jks 

Certificate fingerprints:
         MD5:  5F:51:32:FD:25:5C:0C:51:DC:56:78:53:02:FA:91:FA
         SHA1: 5E:F5:69:A6:EB:BC:BF:5A:87:16:EF:52:1A:77:00:E3:04:B6:0A:A1
         SHA256: 99:D6:02:5F:F5:09:1B:2E:14:27:7C:22:A8:8F:F4:8B:EA:22:67:53:A1:90:E7:89:56:8A:72:06:A6:1D:08:CD

**Comment by wangzhaohe** [comment]
> 

可以了，我加上下面一段 dubug 就行了。app/build.gradle

     signingConfigs {
          // release配置完全替换成此，主要是读取key.properties文件内容
          release {
              keyAlias keystoreProperties['keyAlias']
              keyPassword keystoreProperties['keyPassword']
              storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
              storePassword keystoreProperties['storePassword']
          }
          // 像此debug模式你可以设置为另外的密钥文件，如果你只是一个密钥的话，可以把debug配置完全注释不去配置
          debug {
              keyAlias "kbed"
              keyPassword "mypassword"
              storeFile file('./kbed.jks')
              storePassword "mypassword"
          }
      }
