### ISSUE TITLE
集成进来的时候可能会爆错

### ISSUE THREAD

**Issue by qyp19911009** [fluttercandies/flutter_bdface_collect#2]
error: Multiple commands produce '/Users/flower/merchant-app/merchant_app/build/ios/Debug-iphoneos/Runner.app/Assets.car':
    1) Target 'Runner' (project 'Runner') has compile command with input '/Users/flower/merchant-app/merchant_app/ios/Runner/Assets.xcassets'
    2) That command depends on command in Target 'Runner' (project 'Runner'): script phase “[CP] Copy Pods Resources”

我的处理方式
# platform :ios, '9'
 install! 'cocoapods', :disable_input_output_paths => true
添加了上面一句话，解决了，我现在是

environment:
  sdk: ">=2.10.0 <3.0.0"
没有使用空安全 

百度到的解决方案是：https://www.jianshu.com/p/1e46bf6c48eb 查看链接处理

**Comment by CyJaySong** [comment]
@qyp19911009 嗯嗯，REDAME里面写了的，那么我关闭这个issue了哦
