### ISSUE TITLE
androind 初始化报错

### ISSUE THREAD

**Issue by skjun** [fluttercandies/flutter_bdface_collect#21]
I/flutter (15830): 开始初始化
E/AndroidRuntime(15830): FATAL EXCEPTION: main
E/AndroidRuntime(15830): java.lang.UnsatisfiedLinkError: dlopen failed: library "libbdface_sdk.so" not found
E/AndroidRuntime(15830): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/AndroidRuntime(15830): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime(15830): 	at java.lang.System.loadLibrary(System.java:1664)
E/AndroidRuntime(15830): 	at com.baidu.idl.main.facesdk.FaceAuth.<clinit>(FaceAuth.java:33)
E/AndroidRuntime(15830): 	at com.baidu.idl.face.platform.FaceSDKManager.<init>(FaceSDKManager.java:54)
E/AndroidRuntime(15830): 	at com.baidu.idl.face.platform.FaceSDKManager.getInstance(FaceSDKManager.java:69)
E/AndroidRuntime(15830): 	at com.fluttercandies.flutter_bdface_collect.FlutterBdfaceCollectPlugin.init(FlutterBdfaceCollectPlugin.java:125)
E/AndroidRuntime(15830): 	at com.fluttercandies.flutter_bdface_collect.FlutterBdfaceCollectPlugin.onMethodCall(FlutterBdfaceCollectPlugin.java:51)
E/AndroidRuntime(15830): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(15830): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(15830): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/AndroidRuntime(15830): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(15830): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(15830): 	at android.os.Looper.loop(Looper.java:183)

**Comment by CyJaySong** [comment]
注意SDK支持的架构，main分支不支持x86，若要在虚拟机上面运行项目，需使用old-sdk分支
