### ISSUE TITLE
您好，我的情况是初始化失败，采集时出现了圆框框可是人脸在里面没有反应，结果是采集超时？（一切的书写应该是没有问题的）

### ISSUE THREAD

**Issue by ItsmeLily688** [fluttercandies/flutter_bdface_collect#23]
初始化结果“errCode: 13, errMsg:  -->local auth failed:4 -> err_no:700 -> err_msg:wrong match of appkey/packedge_name/signature_md5 -->remote auth failed:13”
这里我是安装了您的flutter_bdface_collect: ^1.1.3
运行调试的时候显示了有一百多个过时情况。

**Comment by ItsmeLily688** [comment]
您好，我的情况是初始化失败，采集时出现了圆框框可是人脸在里面没有反应，结果是采集超时？（一切的书写应该是没有问题的）
Hello, my case is the initialization failed, the acquisition appeared when the round box box but the face in it does not respond, the result is the acquisition timeout? (Everything should be written without problems)

**Comment by CyJaySong** [comment]
err_msg:wrong match of appkey/packedge_name/signature_md5
这就是初始化失败的原因，签名验证不过，请验证一下你在百度智能云申请授权的Appkey，apk包名，以及签名MD5是否匹配，签名MD5不是签名文件的MD5

**Comment by ItsmeLily688** [comment]
我将百度智能云申请后得到的sample文件里的“idl-license.face-android”和“quality_config.json”复制到我自己的项目里，验证应该没有问题。目前检查后，仍然是这个问题，不知道怎么解决？

**Comment by ItsmeLily688** [comment]
签名MD5不是签名文件的MD5，不太明白。

**Comment by ItsmeLily688** [comment]
![image](https://user-images.githubusercontent.com/110664503/183560453-34619111-cca0-4aab-b264-94ae38ae0832.png)
现在又出现了新的问题。

**Comment by ItsmeLily688** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Changes are not tracked, unable determine incremental changes.
  目前惟一的问题，不太清楚怎么回事？

**Comment by ItsmeLily688** [comment]
![image](https://user-images.githubusercontent.com/110664503/183801305-28d7fbd0-4d83-44e9-827f-8bbe54ffd6ea.png)
![image](https://user-images.githubusercontent.com/110664503/183801323-bada481f-2b68-4df6-9caa-56b96ad088e1.png)
![image](https://user-images.githubusercontent.com/110664503/183801351-f45bc32a-8273-4072-b236-c32a6cd3de72.png)
![image](https://user-images.githubusercontent.com/110664503/183801387-5808e109-ffb1-4efc-bed2-86457194c831.png)
![image](https://user-images.githubusercontent.com/110664503/183801440-66bdeda3-8864-4aed-b7dd-1c1f3ec99539.png)
![image](https://user-images.githubusercontent.com/110664503/183801609-6ff36020-1832-42a9-b61b-65ab8220d45d.png)
![image](https://user-images.githubusercontent.com/110664503/183801805-b362f067-a403-47a8-ac1c-938591e304ac.png)
![image](https://user-images.githubusercontent.com/110664503/183801835-46d8701f-36ba-43fd-97a6-22ad9f38a123.png)
![image](https://user-images.githubusercontent.com/110664503/183801860-1a336fb5-c2dc-45d5-961f-c002fb05be25.png)
![image](https://user-images.githubusercontent.com/110664503/183801877-a97cbfaa-c0cb-448d-b3f7-e271c449413b.png)
![image](https://user-images.githubusercontent.com/110664503/183801890-fa7c73b1-3253-4709-9644-0a3e7257f54a.png)
![image](https://user-images.githubusercontent.com/110664503/183801910-2788e8ee-a548-4c98-b8d0-5462af4f0e03.png)

**Comment by ItsmeLily688** [comment]
![image](https://user-images.githubusercontent.com/110664503/183802125-0dd86447-8a50-4b80-bbac-a1b7b64a423d.png)
作者您好，我的初始化一直不成功，配置似乎是没有问题，不清楚问题在哪？感谢。

**Comment by CyJaySong** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/29367599/184063621-3225165d-390e-4075-b4cf-191cfb006ddd.png">
依然是签名校验不对呀
