### ISSUE TITLE
如何实现横屏显示？

### ISSUE THREAD

**Issue by lakerszhy** [fluttercandies/flutter_bdface_collect#25]
想在平板上横屏显示，应该如何实现？
谢谢。

**Comment by CyJaySong** [comment]
插件是移植的百度Demo的界面案例，并未适配横屏

**Comment by CyJaySong** [comment]
若要实现横屏的话，你可能得自己写了

**Comment by lakerszhy** [comment]
> 若要实现横屏的话，你可能得自己写了

实现横屏界面后，不能识别到人脸了。是不是需要在某个方法里旋转图片？多谢。

**Comment by ItsmeLily688** [comment]
楼主有可能共享下代码文件吗？我一直运行不了。

**Comment by lakerszhy** [comment]
> 楼主有可能共享下代码文件吗？我一直运行不了。

具体错误是什么呢？

**Comment by ItsmeLily688** [comment]
现在面临的问题是，采集成功后会自动返回上一页面，希望可以跳转到我指定的页面。

**Comment by lakerszhy** [comment]
> 现在面临的问题是，采集成功后会自动返回上一页面，希望可以跳转到我指定的页面。

在Flutter端得到返回结果后，再处理跳转就可以吧？

**Comment by CyJaySong** [comment]
@ItsmeLily688  可以采用上面说的，在Flutter端得到返回结果后，再处理跳转；直接跳转指定页面，在指定页面的initState里调用一个async函数发起采集，async函数等待到采集结果后setState
