### ISSUE TITLE
安卓平台 应用宝和小米商店检测到隐私合规问题

### ISSUE THREAD

**Issue by supermebing** [fluttercandies/flutter_bdface_collect#29]
感谢作者做的功能插件
这次在上架小米商店和应用宝的过程中 反馈了隐私政策合规问题

com.zilue.beehivej/com.baidu.liantian.LiantianReceiver action=android.intent.action.BOOT_COMPLETED

com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1391)<---com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:176)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.os.HandlerThread.run(HandlerThread.java:65)<---com.android.server.ServiceThread.run(ServiceThread.java:46)

应用自启动的问题  请教怎么解决

**Comment by CyJaySong** [comment]
删除掉这部分，然后试试能不能正常使用，能的话，我就提交新的插件版本
![image](https://user-images.githubusercontent.com/29367599/212246650-a5dab012-7285-4482-833f-8d48889d5b0a.png)

**Comment by CyJaySong** [comment]
@supermebing 麻烦反馈一下结果

**Comment by supermebing** [comment]
@CyJaySong  今天重新提交了一遍更新 目前反馈的报告检测正常   删除了图中标红的代码
