### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by meixiaohei** [fluttercandies/flutter_bdface_collect#3]
java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt: open failed: ENOENT (No such file or directory)
![image](https://user-images.githubusercontent.com/33745879/128686218-eab055de-a4bc-4a13-8b97-71bce6277a00.png)
![image](https://user-images.githubusercontent.com/33745879/128686269-689ff246-63d4-45e5-ae2e-fc4acac085d0.png)

**Comment by meixiaohei** [comment]
我少配置什么了吗?

**Comment by Tsuj100** [comment]
@meixiaohei +1

**Comment by Tsuj100** [comment]
我的之前是正常的，现在也是这样了

**Comment by CyJaySong** [comment]
看你直接运行的插件的example，这个肯定不行的啦，你的百度智能云没有申请这个包名的授权。要是实验该插件，请开项目引用该插件，并且在百度智能云申请授权

**Comment by CyJaySong** [comment]
@meixiaohei 如果没有问题我就关闭了

**Comment by wangzhaohe** [comment]
我的 Android 也是报这个错，ios的可以正常采集。
