### ISSUE TITLE
安卓初始化错误！

### ISSUE THREAD

**Issue by 312236232** [fluttercandies/flutter_bdface_collect#31]
E/License-SDK(19027): open license file error.
E/License-SDK(19027): read_license_from_data file not found
E/License-SDK(19027): read_license_from_asset
E/License-SDK(19027): write_license_content
I/bdface  (19027): 参数是：{"mh":"offlineSdkStatistic","dt":{"analysisType":"offline_Sdk","deviceId":"11140C1F12FEEB2C52DFBE8E1D64FADC09","cpuCore":8,"cpuBit":0,"ghz":2016,"ram":1856,"networkType":1,"networkDesc":"WIFI网络","os":1,"osVersion":"10","sdk":1,"sdkVersion":"4.1"}}
E/License-SDK(19027): license file info =0B700C7CF0A20862671F5DD7432F57CDB0D588FEB7C648E03A2C3357E9CA6F8026541C25B8B945FE08DACEFF88AB149F8CD12323CFB8C53A27AA207D72EAA1CA7DF6F884B61FC5D0863FB52A5EC4E89C8BDC0112CC77A2F5B876B69457B66719CB82957F05DC8A6CFF9933B2DC7CA4EA5DE8473A1279158FFB1A96FDCCE84DEAF4820C4598741CE722C51F1576607F3F200BE8B1D32ADE32D1021D
I/DpmTcmClient(19027): RegisterTcmMonitor from: $Proxy0
E/zxq     (19027): request code 200
E/zxq     (19027): request data {"code":0,"msg":"success","result":null}
I/bdface  (19027): response结果：{"code":0,"msg":"success","result":null}
E/License-SDK(19027): request get_remote_license =https://aip.baidubce.com/public/2.0/license/face-api/app/querydevicelicense
E/License-SDK(19027): request code 200
E/License-SDK(19027): request data {"err_no":301,"err_msg":"such app not exists","result":[],"timestamp":1675817448,"cached":0,"serverlogid":"3048446431","error_code":301,"error_msg":"such app not exists"}
E/jni     (19027): java result = {"err_no":301,"err_msg":"such app not exists","result":[],"timestamp":1675817448,"cached":0,"serverlogid":"3048446431","error_code":301,"error_msg":"such app not exists"}

**Comment by 312236232** [comment]
怎么提示，没有这个 app？

**Comment by 312236232** [comment]
属于验证失败，是哪个环节出问题了？

**Comment by CyJaySong** [comment]
包名是否对得上

**Comment by 312236232** [comment]
包名是对的，我再确认下！

**Comment by 312236232** [comment]
没有别的原因？

**Comment by 312236232** [comment]
是对的啊，就是  com.sanyi.sunong

**Comment by 312236232** [comment]
解决了!
因为粗心，没有填对，lienceid
if (Platform.isAndroid) licenseId = "demo-face-android";
else if (Platform.isIOS) licenseId = "demo-face-ios";

感谢作者，这个插件很好，加油！
