### ISSUE TITLE
[Discussions] ios打开采集闪退

### ISSUE THREAD

**Issue by cl549723678** [fluttercandies/flutter_bdface_collect#33]
### Content

ios初始化没报错,但是打开采集就闪退
![QQ截图20230512165023](https://github.com/fluttercandies/flutter_bdface_collect/assets/21279227/108b6e7e-c418-4a68-8df7-059a40050013)

![QQ截图20230512164955](https://github.com/fluttercandies/flutter_bdface_collect/assets/21279227/4c188e5d-1286-4aa1-819f-ce6f415e5925)

**Comment by yj229201093** [comment]
是的，使用1.1.5 以上闪退，1.1.4 正常

**Comment by CyJaySong** [comment]
好的，我今天排查一下

**Comment by CyJaySong** [comment]
好了，有几个资源文件忘了导入
https://github.com/fluttercandies/flutter_bdface_collect/commit/21de3738b9148d4de3250d151a61f5808e73834d
