### ISSUE TITLE
ios人脸识别后，关闭page释放资源，在进入page释放资源后会卡死。

### ISSUE THREAD

**Issue by cl136787252** [fluttercandies/flutter_bdface_collect#5]
ios系统：14.7.1
插件版本：1.0.4
执行await FlutterBdfaceCollect.instance.collect(config)人脸识别后，关闭page释放资源执行FlutterBdfaceCollect.instance.unInit()，然后再次进入Page,不管有没有执行 FlutterBdfaceCollect.instance.collect(config)，在界面销毁释放资源后返回上一个界面会卡死。xocde定位是释放的资源方法报错。怎么解决？
<img width="996" alt="lALPDhmOwlK8PDHNBKbNB8g_1992_1190" src="https://user-images.githubusercontent.com/12270498/130185770-8bbdee9d-1de8-41d9-865d-0c3646caf6b7.png">
<img width="1014" alt="lALPDg7mRmRovEbNBMDNB-w_2028_1216" src="https://user-images.githubusercontent.com/12270498/130185783-7e10ac4c-78f9-4acb-aaf9-8459a12a5639.png">

**Comment by CyJaySong** [comment]
第一次回收可以，第二次回收就出错吗？

**Comment by CyJaySong** [comment]
@cl136787252 经测试，没发现该问题。只有未初始化情况下调用unInit会这样。你应该是多次调用了unInit。建议排查一下声明周期中是哪里多次调用了
