### ISSUE TITLE
[Feature request] 离线采集百度好像下线了，有新的方案吗

### ISSUE THREAD

**Issue by yj229201093** [fluttercandies/flutter_bdface_collect#50]
### Platforms

dart

### Description

离线采集百度好像下线了，有新的方案吗

### Why

离线采集百度好像下线了，有新的方案吗

**Comment by CyJaySong** [comment]
没下线呀
![image](https://github.com/user-attachments/assets/3284f8b2-7660-4ca8-be17-9572d02efbed)
