### ISSUE TITLE
ios 插件覆盖ios的appicon

### ISSUE THREAD

**Issue by cl136787252** [fluttercandies/flutter_bdface_collect#7]
我现在使用这个插件，运行，打包，ios的的appicon这个插件覆盖成了flutter默认的图标。这个问题有好的处理办法吗。
我注释掉这个插件，运行，打包，ios的的appicon是显示正常的。

**Comment by CyJaySong** [comment]
你用的哪个版本？最新版的不会替换啊。之前的版本因为替换App图标资源我忘了删AppIcon.appiconset。新版的不会的

**Comment by cl136787252** [comment]
flutter_bdface_collect: ^1.0.4这个版本的插件。

> 你用的哪个版本？最新版的不会替换啊。之前的版本因为替换App图标资源我忘了删AppIcon.appiconset。新版的不会的

flutter_bdface_collect: ^1.0.4这个版本的插件。

**Comment by CyJaySong** [comment]
你检查一下你工程的图标资源文件是什么，如果跟插件里面有重名，建议改一下被重名的资源文件名称。
![image](https://user-images.githubusercontent.com/29367599/133356450-39d57a34-c3c4-44d0-b1a5-8dd89c4d0957.png)
![image](https://user-images.githubusercontent.com/29367599/133356542-e783fae2-ead7-43c1-b48a-66e8cdd2ad75.png)

**Comment by cl136787252** [comment]
> 你检查一下你工程的图标资源文件是什么，如果跟插件里面有重名，建议改一下被重名的资源文件名称。
> ![image](https://user-images.githubusercontent.com/29367599/133356450-39d57a34-c3c4-44d0-b1a5-8dd89c4d0957.png)
> ![image](https://user-images.githubusercontent.com/29367599/133356542-e783fae2-ead7-43c1-b48a-66e8cdd2ad75.png)

感谢作者!按你的方法解决了图标覆盖的问题。万分感谢！！

**Comment by lance730** [comment]
用1.1.3还是出现这个问题。appIcon改名字是可以的。launchImage读取不到，改名字也不行。assets下面的图片都读取不到了，怎么处理。

**Comment by CyJaySong** [comment]
@lance730 我们没有复现出，你最好是flutter clean一下再试试

**Comment by anchao-lu** [comment]
v1.1.4 还是出现 appIcon 被替换和启动图丢失问题

**Comment by CyJaySong** [comment]
@anchao-lu 请更改资源文件

**Comment by anchao-lu** [comment]
> 

意思就是，项目里面的默认 AppIcon 和 LaunchImage 必须改成其他的？但是我看插件里面没有这两个文件，为啥还是会覆盖呀，我是把插件拉下来，删除了 example 的

**Comment by CyJaySong** [comment]
@anchao-lu 别跟这些重复就好了
<img width="407" alt="image" src="https://user-images.githubusercontent.com/29367599/224619905-4ca3a74e-589e-4c90-b802-c4a454c13a42.png">

**Comment by anchao-lu** [comment]
> @anchao-lu 别跟这些重复就好了 <img alt="image" width="407" src="https://user-images.githubusercontent.com/29367599/224619905-4ca3a74e-589e-4c90-b802-c4a454c13a42.png">

有点奇怪的，我项目里面只有三个图片：AppIcon、LaunchImage 和一张 logo 图片，都没有和插件资源里面的重复。但是还是会把 AppIcon 修改为 Flutter 默认的，然后 LaunchImage 变成空白

**Comment by lakerszhy** [comment]
修改图标资源文件后，AppIcon和启动页都能显示了，但在启动页和Flutter第一个页面之间还是会出现白屏现象，请问应该怎么解决？

**Comment by CyJaySong** [comment]
@anchao-lu 最好是检查一下本地资源是不是已经被替换了，被替换了的话，恢复回去再按照之前给的解决办法处理。最近发现百度SDK也更新了，我抽时间重新资源引用方式吧

**Comment by CyJaySong** [comment]
https://github.com/fluttercandies/flutter_bdface_collect/commit/ed06c9ec91a37523a1a3df83f28e2251902c974e
已修改资源引入方式，无需使用 `install! 'cocoapods', :disable_input_output_paths => true`

**Comment by CyJaySong** [comment]
@lance730 @anchao-lu @gzlock @cl136787252
