### ISSUE TITLE
android 集成之后闪退

### ISSUE THREAD

**Issue by NiBoTe** [fluttercandies/flutter_bdface_collect#9]
I/flutter ( 1641): 开始初始化
W/linker  ( 1641): Warning: "/data/app/com.fluttercandies.flutter_bdface_collect_example-ysjrr808Vvqc_qQyRdK05Q==/lib/arm64/libpaddle_light_api_shared.so" unused DT entry: DT_RPATH (type 0xf arg 0x8a19) (ignoring)
E/License-SDK( 1641): bd_unifylicense load start
E/License-SDK( 1641): bd_unifylicense load end
W/Thread-4( 1641): type=1400 audit(0.0:56712): avc: denied { search } for pid=1641 name="block" dev="tmpfs" ino=10441 scontext=u:r:untrusted_app:s0:c235,c256,c512,c768 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0
I/License-SDK( 1641): Load liantian ac succeed
W/Thread-4( 1641): type=1400 audit(0.0:56713): avc: denied { search } for pid=1641 name="block" dev="tmpfs" ino=10441 scontext=u:r:untrusted_app:s0:c235,c256,c512,c768 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0
I/QarthLog( 1641): [PatchStore] createDisableExceptionQarthFile
I/QarthLog( 1641): [PatchStore] create disable file for com.fluttercandies.flutter_bdface_collect_example uid is 10235
E/AndroidRuntime( 1641): FATAL EXCEPTION: Thread-5
E/AndroidRuntime( 1641): Process: com.fluttercandies.flutter_bdface_collect_example, PID: 1641
E/AndroidRuntime( 1641): java.lang.UnsupportedOperationException: SDK Self Check: Provider Error,
E/AndroidRuntime( 1641): 	at com.baidu.liantian.g.d.j(CommonMethods.java:1497)
E/AndroidRuntime( 1641): 	at com.baidu.liantian.core.d$1.run(MethodImpl.java:63)
E/AndroidRuntime( 1641): 	at java.lang.Thread.run(Thread.java:929)
E/RtgSchedManager( 1641): endActivityTransaction: margin state not match
E/RtgSchedManager( 1641): endActivityTransaction: margin state not match
D/DecorView( 1641): showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
I/Process ( 1641): Sending signal. PID: 1641 SIG: 9
Lost connection to device.

**Comment by NiBoTe** [comment]
initState  调用了 await FlutterBdfaceCollect.instance.init(licenseId); licenseId 用的百度云授权过的。

**Comment by CyJaySong** [comment]
包名是否对得上。example 的包名是com.fluttercandies.flutter_bdface_collect_example

**Comment by NiBoTe** [comment]
![image](https://user-images.githubusercontent.com/24713845/144341519-f4851246-61b7-417b-ae00-b5e1572eb38a.png)
用的是这个包名

**Comment by CyJaySong** [comment]
![image](https://user-images.githubusercontent.com/29367599/144341771-fea9fcae-90ec-4b82-aef1-d7d751fae7ec.png)
![image](https://user-images.githubusercontent.com/29367599/144341815-bb94963c-afc2-4517-8093-b0c7864ee52c.png)

**Comment by NiBoTe** [comment]
![image](https://user-images.githubusercontent.com/24713845/144344036-9d17ca98-67f8-41fc-9a9b-38fa41a30e8c.png)
我的证书 包名  都替换成一样的了，老板帮我看看

**Comment by CyJaySong** [comment]
> ![image](https://user-images.githubusercontent.com/24713845/144344036-9d17ca98-67f8-41fc-9a9b-38fa41a30e8c.png) 我的证书 包名 都替换成一样的了，老板帮我看看

你是 debug 么？debug 的话主要替换 debug 的签名啊。你在百度注册的时候肯定用的release的签名吧
